# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: navidagz
          filename: metrics.svg
          template: classic
          
          base: header, activity, community
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          
          config_display: large
          config_padding: 0, 10 + 8%
          config_timezone: Europe/Stockholm
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_analysis_timeout_repositories: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 180
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # plugin_lines: yes
          # plugin_lines_history_limit: 1
          # plugin_lines_repositories_limit: 4
          # plugin_lines_sections: base

          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

          # plugin_habits: yes
          # plugin_habits_facts: yes
          # plugin_habits_charts: yes

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: no
          plugin_notable_indepth: no
          plugin_notable_types: pull_request, commit, issue
